name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install


      - name: SSH into EC2 instace and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            set -e
            echo "Pulling latest changes on EC2"
            cd ${{ secrets.EC2_APP_PATH }}
            git reset --hard
            git pull origin main
            echo "Installing dependencies"
            npm install 
            echo "Restarting application"
            pm2 restart app || pm2 start index.js --name app
